/** ~150 package catalog seed rows from screenshot pages (1 entry per table row). */

export type PackageSeedRow = {
  name: string
  sessions: number
  branch: 'San Mateo, Rizal' | 'Cainta, Rizal' | 'Pasig City' | 'Warehouse' | 'Lipa, Batangas' | 'Dasmariñas, Cavite' | 'Bacoor, Cavite' | ''
  status: 'active' | 'inactive'
  price: number
}

export const PACKAGE_CATALOG_SEED: PackageSeedRow[] = [
  // PAGE1
  { name: 'SECY FACE', sessions: 5, branch: 'San Mateo, Rizal', status: 'active', price: 15000 },
  { name: 'SEXY CURVES', sessions: 5, branch: 'San Mateo, Rizal', status: 'active', price: 16000 },
  { name: 'SEXY BACK', sessions: 5, branch: 'San Mateo, Rizal', status: 'active', price: 16000 },
  { name: 'PICO STRETCH MARK', sessions: 10, branch: 'Cainta, Rizal', status: 'active', price: 5000 },
  { name: 'SLIM PACKAGE', sessions: 10, branch: 'Cainta, Rizal', status: 'active', price: 15000 },
  { name: 'SELF LOVE GLOW UP', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 12500 },
  { name: 'SELF LOVE GLOW UP', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 12500 },
  { name: 'SELF LOVE GLOW UP', sessions: 1, branch: 'Pasig City', status: 'active', price: 12500 },
  { name: 'ULTRA FORMER 12D HIFU', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 10000 },
  { name: 'ULTRA FORMER 12D HIFU', sessions: 1, branch: 'Pasig City', status: 'active', price: 10000 },
  // PAGE2
  { name: 'MESOSLIM FACE CONTOUR', sessions: 5, branch: 'Cainta, Rizal', status: 'active', price: 15000 },
  { name: 'MESOSLIM FACE CONTOUR', sessions: 5, branch: 'Pasig City', status: 'active', price: 15000 },
  { name: 'MESOSLIM ARMS CONTOUR', sessions: 5, branch: 'Cainta, Rizal', status: 'active', price: 15000 },
  { name: 'MESOSLIM ARMS CONTOUR', sessions: 5, branch: 'Pasig City', status: 'active', price: 15000 },
  { name: 'MESOSLIM SEXY BACK CONTOUR', sessions: 5, branch: 'Cainta, Rizal', status: 'active', price: 16000 },
  { name: 'MESOSLIM SEXY BACK CONTOUR', sessions: 5, branch: 'Pasig City', status: 'active', price: 16000 },
  { name: 'MESOSLIM LOVE HANDLE CONTOUR', sessions: 5, branch: 'Cainta, Rizal', status: 'active', price: 16000 },
  { name: 'MESOSLIM LOVE HANDLE CONTOUR', sessions: 5, branch: 'Pasig City', status: 'active', price: 16000 },
  { name: 'MESOSLIM TUMMY CONTOUR', sessions: 5, branch: 'Cainta, Rizal', status: 'active', price: 16000 },
  { name: 'MESOSLIM TUMMY CONTOUR', sessions: 5, branch: 'Pasig City', status: 'active', price: 16000 },
  // PAGE3
  { name: 'MESOSLIM LEGS CONTOUR', sessions: 5, branch: 'Cainta, Rizal', status: 'active', price: 16000 },
  { name: 'MESOSLIM LEGS CONTOUR', sessions: 5, branch: 'Pasig City', status: 'active', price: 16000 },
  { name: 'LEMON BOTTLE', sessions: 3, branch: 'San Mateo, Rizal', status: 'active', price: 15000 },
  { name: 'LEMON BOTTLE', sessions: 3, branch: 'Cainta, Rizal', status: 'active', price: 15000 },
  { name: 'LEMON BOTTLE', sessions: 3, branch: 'Pasig City', status: 'active', price: 15000 },
  { name: 'IMAJICA SLIM GLP1', sessions: 4, branch: 'Cainta, Rizal', status: 'active', price: 30000 },
  { name: 'IMAJICA SLIM GLP1', sessions: 4, branch: 'Pasig City', status: 'active', price: 30000 },
  { name: 'IMMUNITY DRIP 25+10', sessions: 35, branch: 'Cainta, Rizal', status: 'active', price: 50000 },
  { name: 'IMMUNITY DRIP 25+10', sessions: 35, branch: 'Pasig City', status: 'active', price: 50000 },
  { name: 'SLENDER DRIP 25+10', sessions: 35, branch: 'San Mateo, Rizal', status: 'active', price: 50000 },
  // PAGE4
  { name: 'SLENDER DRIP 25+10', sessions: 35, branch: 'Cainta, Rizal', status: 'active', price: 50000 },
  { name: 'SLENDER DRIP 25+10', sessions: 35, branch: 'Pasig City', status: 'active', price: 50000 },
  { name: 'AGE REVERSING DRIP 5+1', sessions: 6, branch: 'San Mateo, Rizal', status: 'active', price: 10000 },
  { name: 'AGE REVERSING DRIP 5+1', sessions: 6, branch: 'Cainta, Rizal', status: 'active', price: 10000 },
  { name: 'AGE REVERSING DRIP 5+1', sessions: 6, branch: 'Pasig City', status: 'active', price: 10000 },
  { name: 'AGE REVERSING DRIP 10+4', sessions: 14, branch: 'San Mateo, Rizal', status: 'active', price: 20000 },
  { name: 'AGE REVERSING DRIP 10+4', sessions: 14, branch: 'Cainta, Rizal', status: 'active', price: 20000 },
  { name: 'AGE REVERSING DRIP 10+4', sessions: 14, branch: 'Pasig City', status: 'active', price: 20000 },
  { name: 'AGE REVERSING DRIP 15+6', sessions: 21, branch: 'San Mateo, Rizal', status: 'active', price: 30000 },
  { name: 'AGE REVERSING DRIP 15+6', sessions: 21, branch: 'Cainta, Rizal', status: 'active', price: 30000 },
  // PAGE5
  { name: 'AGE REVERSING DRIP 15+6', sessions: 21, branch: 'Pasig City', status: 'active', price: 30000 },
  { name: 'AGE REVERSING DRIP 25+10', sessions: 35, branch: 'San Mateo, Rizal', status: 'active', price: 50000 },
  { name: 'AGE REVERSING DRIP 25+10', sessions: 35, branch: 'Cainta, Rizal', status: 'active', price: 50000 },
  { name: 'AGE REVERSING DRIP 25+10', sessions: 35, branch: 'Pasig City', status: 'active', price: 50000 },
  { name: 'MULTIVITAMIN DRIP 5+1', sessions: 6, branch: 'San Mateo, Rizal', status: 'active', price: 12500 },
  { name: 'MULTIVITAMIN DRIP 5+1', sessions: 6, branch: 'Cainta, Rizal', status: 'active', price: 12500 },
  { name: 'MULTIVITAMIN DRIP 5+1', sessions: 6, branch: 'Pasig City', status: 'active', price: 12500 },
  { name: 'MULTIVITAMIN DRIP 10+5', sessions: 15, branch: 'San Mateo, Rizal', status: 'active', price: 25000 },
  { name: 'MULTIVITAMIN DRIP 10+5', sessions: 15, branch: 'Cainta, Rizal', status: 'active', price: 25000 },
  { name: 'MULTIVITAMIN DRIP 10+5', sessions: 15, branch: 'Pasig City', status: 'active', price: 25000 },
  // PAGE6
  { name: 'MULTIVITAMIN DRIP 15+9', sessions: 24, branch: 'San Mateo, Rizal', status: 'active', price: 37500 },
  { name: 'MULTIVITAMIN DRIP 15+9', sessions: 24, branch: 'Cainta, Rizal', status: 'active', price: 37500 },
  { name: 'MULTIVITAMIN DRIP 15+9', sessions: 24, branch: 'Pasig City', status: 'active', price: 37500 },
  { name: 'MULTIVITAMIN DRIP 20+15', sessions: 35, branch: 'San Mateo, Rizal', status: 'active', price: 50000 },
  { name: 'MULTIVITAMIN DRIP 20+15', sessions: 35, branch: 'Cainta, Rizal', status: 'active', price: 50000 },
  { name: 'MULTIVITAMIN DRIP 20+15', sessions: 35, branch: 'Pasig City', status: 'active', price: 50000 },
  { name: 'RADIANT EYE', sessions: 5, branch: '', status: 'active', price: 5000 },
  { name: 'K-GLOW PACKAGE', sessions: 5, branch: '', status: 'active', price: 7500 },
  { name: 'CHARCOAL LASER', sessions: 5, branch: '', status: 'active', price: 7500 },
  { name: 'PICO LASER', sessions: 5, branch: '', status: 'active', price: 7500 },
  // PAGE7
  { name: 'OXYGBRIGHT FACIAL', sessions: 5, branch: '', status: 'active', price: 7500 },
  { name: 'ACNE CURE FACIAL', sessions: 5, branch: '', status: 'active', price: 7500 },
  { name: 'IMAJICA AQUA', sessions: 5, branch: '', status: 'active', price: 5000 },
  { name: 'IMAJICA CELEBRITY PACKAGE', sessions: 5, branch: '', status: 'active', price: 15000 },
  { name: 'IMAJICA CLEAR (FACE)', sessions: 5, branch: '', status: 'active', price: 15000 },
  { name: 'IMAJICA CLEAR (CHEST)', sessions: 5, branch: '', status: 'active', price: 15000 },
  { name: 'IMAJICA CLEAR (BACK)', sessions: 5, branch: '', status: 'active', price: 15000 },
  { name: 'IMAJICA CLEAR (CHEST AND BACK)', sessions: 5, branch: '', status: 'active', price: 25000 },
  { name: 'IMAJICA REVIVE', sessions: 5, branch: '', status: 'active', price: 25000 },
  { name: 'IMAJICA MESODNA', sessions: 5, branch: '', status: 'active', price: 25000 },
  // PAGE8
  { name: 'IMAJICA VAMPIRE FACIAL', sessions: 5, branch: '', status: 'active', price: 20000 },
  { name: 'IMAJICA MESOMELA', sessions: 5, branch: '', status: 'active', price: 25000 },
  { name: 'CHARCOAL LASER (UNDERARMS)', sessions: 5, branch: '', status: 'active', price: 7000 },
  { name: 'CHARCOAL LASER (NAPE)', sessions: 5, branch: '', status: 'active', price: 7000 },
  { name: 'CHARCOAL LASER (ELBOW)', sessions: 5, branch: '', status: 'active', price: 7000 },
  { name: 'CHARCOAL LASER (KNEE)', sessions: 5, branch: '', status: 'active', price: 7000 },
  { name: 'CHARCOAL LASER (BUTT)', sessions: 5, branch: '', status: 'active', price: 9500 },
  { name: 'CHARCOAL LASER (BIKINI)', sessions: 5, branch: '', status: 'active', price: 9500 },
  { name: 'DIODE (UPPER LIP)', sessions: 10, branch: '', status: 'active', price: 3000 },
  { name: 'DIODE (FULL FACE)', sessions: 10, branch: '', status: 'active', price: 10000 },
  // PAGE9
  { name: 'DIODE (UNDERARMS)', sessions: 10, branch: '', status: 'active', price: 10000 },
  { name: 'DIODE (FULL ARMS)', sessions: 10, branch: '', status: 'active', price: 10000 },
  { name: 'DIODE (BRAZILLIAN)', sessions: 10, branch: '', status: 'active', price: 15000 },
  { name: 'DIODE (HALF LEGS)', sessions: 10, branch: '', status: 'active', price: 15000 },
  { name: 'DIODE (FULL LEGS)', sessions: 10, branch: '', status: 'active', price: 25000 },
  { name: 'IMAJICA BRIGHT INTIMATE', sessions: 8, branch: '', status: 'active', price: 20000 },
  { name: 'IMAJICA FLAWLESS INTIMATE', sessions: 10, branch: '', status: 'active', price: 20000 },
  { name: 'IMAJICA BRIGHT BUTT', sessions: 8, branch: '', status: 'active', price: 20000 },
  { name: 'IMAJICA BRIGHT UNDERARM', sessions: 8, branch: '', status: 'active', price: 15000 },
  { name: 'IMAJICA FLAWLESS UNDERARM', sessions: 10, branch: '', status: 'active', price: 15000 },
  // PAGE10
  { name: 'ASCE (FOR FACE)', sessions: 5, branch: '', status: 'active', price: 50000 },
  { name: 'ASCE (FOR HAIR)', sessions: 5, branch: '', status: 'active', price: 50000 },
  { name: 'ASCE (FOR INTIMATE)', sessions: 5, branch: '', status: 'active', price: 75000 },
  { name: 'CROWNING GLORY', sessions: 8, branch: '', status: 'active', price: 35000 },
  { name: 'MESOSLIM FACE', sessions: 5, branch: '', status: 'active', price: 15000 },
  { name: 'MESOSLIM ARMS', sessions: 5, branch: '', status: 'active', price: 15000 },
  { name: 'MESOSLIM BRALINE', sessions: 5, branch: '', status: 'active', price: 16000 },
  { name: 'MESO LOVE HANDLE', sessions: 5, branch: '', status: 'active', price: 16000 },
  { name: 'MESOSLIM TUMMY', sessions: 5, branch: '', status: 'active', price: 16000 },
  { name: 'MESOSLIM BUTT', sessions: 5, branch: '', status: 'active', price: 16000 },
  // PAGE11
  { name: 'MESOSLIM LEGS', sessions: 5, branch: '', status: 'active', price: 16000 },
  { name: 'SLIMMING PROGRAM (LEMON BOTTLE 3 VIALS)', sessions: 1, branch: '', status: 'active', price: 15000 },
  { name: 'MICRONEEDLING', sessions: 5, branch: '', status: 'active', price: 10000 },
  { name: 'RED CELL MICRONEEDLING', sessions: 5, branch: '', status: 'active', price: 20000 },
  { name: 'PRP VAMPIRE', sessions: 5, branch: '', status: 'active', price: 20000 },
  { name: 'SPANISH PEEL', sessions: 5, branch: '', status: 'active', price: 20000 },
  { name: 'TCA PEEL', sessions: 5, branch: '', status: 'active', price: 20000 },
  { name: 'SUBCISION', sessions: 5, branch: '', status: 'active', price: 20000 },
  { name: 'RADIANT GLOW PUSH', sessions: 10, branch: '', status: 'active', price: 4000 },
  { name: 'REJURAN HEALER', sessions: 5, branch: '', status: 'active', price: 100000 },
  // PAGE12
  { name: 'REJURAN HB (HYDRATION)', sessions: 5, branch: '', status: 'active', price: 50000 },
  { name: 'REJURAN I (UNDEREYE)', sessions: 5, branch: '', status: 'active', price: 50000 },
  { name: 'REJURAN S (SCARS)', sessions: 5, branch: '', status: 'active', price: 50000 },
  { name: 'SLENDER 5+1', sessions: 6, branch: '', status: 'active', price: 10000 },
  { name: 'AGE-REVERSING 5+1', sessions: 6, branch: '', status: 'active', price: 10000 },
  { name: 'MULTIVITAMINS 5+1', sessions: 6, branch: '', status: 'active', price: 12500 },
  { name: 'IMMUNITY 10+4', sessions: 14, branch: '', status: 'active', price: 20000 },
  { name: 'IMMUNITY 5+1', sessions: 6, branch: '', status: 'active', price: 10000 },
  { name: 'SLENDER 10+4', sessions: 14, branch: '', status: 'active', price: 20000 },
  { name: 'AGE-REVERSING 10+4', sessions: 14, branch: '', status: 'active', price: 20000 },
  // PAGE13
  { name: 'MULTIVITAMINS 10+5', sessions: 15, branch: '', status: 'active', price: 25000 },
  { name: 'IMMUNITY 15+6', sessions: 21, branch: '', status: 'active', price: 30000 },
  { name: 'SLENDER 15+6', sessions: 21, branch: '', status: 'active', price: 30000 },
  { name: 'AGE-REVERSING 15+6', sessions: 21, branch: '', status: 'active', price: 30000 },
  { name: 'MULTIVITAMINS 15+6', sessions: 21, branch: '', status: 'active', price: 37500 },
  { name: 'ULTRAFORMER', sessions: 1, branch: '', status: 'active', price: 10000 },
  { name: 'HIKO THREADS', sessions: 1, branch: '', status: 'active', price: 20000 },
  { name: 'IMAJICA HAPPY HOUR', sessions: 3, branch: '', status: 'active', price: 2500 },
  { name: 'IMAJICA CLEAR PACKAGE', sessions: 25, branch: '', status: 'active', price: 15000 },
  { name: 'CLEANSING FACIAL', sessions: 5, branch: '', status: 'active', price: 15000 },
  // PAGE14
  { name: 'ACNE CURE TREATMENT', sessions: 5, branch: '', status: 'active', price: 15000 },
  { name: 'CARBON BLACK DOLL LASER', sessions: 5, branch: '', status: 'active', price: 15000 },
  { name: 'CALMING MASK', sessions: 5, branch: '', status: 'active', price: 15000 },
  { name: 'LIGHT THERAPY', sessions: 5, branch: '', status: 'active', price: 15000 },
  { name: 'DIAMOND PEEL', sessions: 5, branch: '', status: 'active', price: 15000 },
  { name: 'OXYBRIGHT', sessions: 5, branch: '', status: 'active', price: 15000 },
  { name: 'GLOW MASK', sessions: 5, branch: '', status: 'active', price: 15000 },
  { name: 'IMAJICA FACE SCULPT', sessions: 1, branch: '', status: 'active', price: 10000 },
  { name: 'LIP BOOSTER', sessions: 4, branch: '', status: 'active', price: 40000 },
  { name: 'HAIR REMOVAL (UPPER LIP)', sessions: 10, branch: '', status: 'active', price: 3000 },
  // PAGE15
  { name: 'HAIR REMOVAL (FULL FACE)', sessions: 10, branch: '', status: 'active', price: 10000 },
  { name: 'HAIR REMOVAL (UNDERARM)', sessions: 10, branch: '', status: 'active', price: 10000 },
  { name: 'HAIR REMOVAL (FULL ARM)', sessions: 10, branch: '', status: 'active', price: 20000 },
  { name: 'HAIR REMOVAL (BRAZILLIAN)', sessions: 10, branch: '', status: 'active', price: 15000 },
  { name: 'HAIR REMOVAL (HALF LEGS)', sessions: 10, branch: '', status: 'active', price: 15000 },
  { name: 'HAIR REMOVAL (FULL LEGS)', sessions: 10, branch: '', status: 'active', price: 25000 },
  { name: 'IMAJICA FACE CONTOUR', sessions: 1, branch: '', status: 'active', price: 10000 },
  { name: 'IMAJICA ARMS CONTOUR', sessions: 1, branch: '', status: 'active', price: 10000 },
  { name: 'IMAJICA LOVE HANDLE CONTOUR', sessions: 1, branch: '', status: 'active', price: 10000 },
  { name: 'IMAJICA UNDER BUTT CONTOUR', sessions: 1, branch: '', status: 'active', price: 10000 },
]
