/** ~510 service catalog seed rows from screenshot pages (1 entry per table row). */

export type ServiceSeedRow = {
  name: string
  sessions: number
  branch: 'San Mateo, Rizal' | 'Cainta, Rizal' | 'Pasig City' | 'Warehouse' | 'Lipa, Batangas' | 'Dasmariñas, Cavite' | 'Bacoor, Cavite' | ''
  status: 'active' | 'inactive'
  price: number
}

export const SERVICE_CATALOG_SEED: ServiceSeedRow[] = [
  { name: 'FLAWLESS UNDERARM PER SESSION', sessions: 1, branch: 'Pasig City', status: 'active', price: 2000 },
  { name: 'RADIANT PUSH PER SESSION', sessions: 1, branch: 'Pasig City', status: 'active', price: 1500 },
  { name: 'PIMPLE INJECT', sessions: 3, branch: 'Pasig City', status: 'active', price: 750 },
  { name: 'IMALICA PREMIUM PACKAGE', sessions: 5, branch: 'Cainta, Rizal', status: 'active', price: 15000 },
  { name: 'IMALICA BRIGHT', sessions: 5, branch: 'Cainta, Rizal', status: 'active', price: 10000 },
  { name: 'IMALICA GLOW PACKAGE', sessions: 5, branch: 'Cainta, Rizal', status: 'active', price: 12000 },
  { name: 'BLACK CARBON FACIAL', sessions: 5, branch: 'Cainta, Rizal', status: 'active', price: 7500 },
  { name: 'ACNE CLEAR FACIAL', sessions: 5, branch: 'Cainta, Rizal', status: 'active', price: 10000 },
  { name: 'FRACTIONAL LASER TX', sessions: 5, branch: 'Cainta, Rizal', status: 'active', price: 15000 },
  { name: 'BEAUTIFUL EYES', sessions: 10, branch: 'Cainta, Rizal', status: 'active', price: 5000 },
  { name: 'MESO DNA', sessions: 5, branch: 'Cainta, Rizal', status: 'active', price: 25000 },
  { name: 'MORPHEUS', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 30000 },
  { name: 'MORPHEUS', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 30000 },
  { name: 'NAPE WHITENING', sessions: 5, branch: 'Cainta, Rizal', status: 'active', price: 9000 },
  { name: 'KNEE AND ELBOW WHITENING', sessions: 5, branch: 'Cainta, Rizal', status: 'active', price: 12000 },
  { name: 'ULTIMATE INTIMATE PACKAGE', sessions: 10, branch: 'Cainta, Rizal', status: 'active', price: 30000 },
  { name: 'BUTT WHITENING PACKAGE', sessions: 5, branch: 'Cainta, Rizal', status: 'active', price: 22000 },
  { name: 'ULTIMATE INTIMATE PACKAGE 2', sessions: 5, branch: 'Cainta, Rizal', status: 'active', price: 20000 },
  { name: 'IMALICA SCULPT', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 10000 },
  { name: 'IMALICA SCULPT PACKAGE', sessions: 3, branch: 'Cainta, Rizal', status: 'active', price: 25000 },
  { name: 'BARBIE FACE', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 2000 },
  { name: 'BARBIE FACE PACKAGE', sessions: 5, branch: 'Cainta, Rizal', status: 'active', price: 15000 },
  { name: 'BARBIE ARMS', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 3500 },
  { name: 'BARBIE ARMS PACKAGE', sessions: 5, branch: 'Cainta, Rizal', status: 'active', price: 15000 },
  { name: 'BARBIE CURVES', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 4000 },
  { name: 'BARBIE CURVES PACKAGE', sessions: 5, branch: 'Cainta, Rizal', status: 'active', price: 16000 },
  { name: 'BARBIE FACE', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 4000 },
  { name: 'BARBIE FACE PACKAGE', sessions: 5, branch: 'Cainta, Rizal', status: 'active', price: 16000 },
  { name: 'VIP SLIMMING PACKAGE', sessions: 5, branch: 'Cainta, Rizal', status: 'active', price: 30000 },
  { name: 'MULTIVITAMIN DRIP 5+1', sessions: 5, branch: 'Cainta, Rizal', status: 'active', price: 12500 },
  { name: 'MULTIVITAMIN DRIP 10+2', sessions: 10, branch: 'Cainta, Rizal', status: 'active', price: 21000 },
  { name: 'MULTIVITAMIN DRIP 15+3', sessions: 15, branch: 'Cainta, Rizal', status: 'active', price: 27500 },
  { name: 'MULTIVITAMIN DRIP 25+5', sessions: 25, branch: 'Cainta, Rizal', status: 'active', price: 42500 },
  { name: 'AGE REVERSING DRIP 10+2', sessions: 10, branch: 'Cainta, Rizal', status: 'active', price: 23000 },
  { name: 'AGE REVERSING DRIP 15+3', sessions: 15, branch: 'Cainta, Rizal', status: 'active', price: 29000 },
  { name: 'AGE REVERSING DRIP 25+5', sessions: 25, branch: 'Cainta, Rizal', status: 'active', price: 50000 },
  { name: 'SLENDER DRIP 10+2', sessions: 10, branch: 'Cainta, Rizal', status: 'active', price: 23000 },
  { name: 'SLENDER DRIP 15+3', sessions: 15, branch: 'Cainta, Rizal', status: 'active', price: 30000 },
  { name: 'SLENDER DRIP 25+5', sessions: 25, branch: 'Cainta, Rizal', status: 'active', price: 50000 },
  { name: 'IMMUNITY DRIP 10+2', sessions: 10, branch: 'Cainta, Rizal', status: 'active', price: 23000 },
  { name: 'IMMUNITY DRIP 15+3', sessions: 15, branch: 'Cainta, Rizal', status: 'active', price: 30000 },
  { name: 'IMMUNITY DRIP 25+5', sessions: 25, branch: 'Cainta, Rizal', status: 'active', price: 50000 },
  { name: 'GLUTA PUSH', sessions: 10, branch: 'Cainta, Rizal', status: 'active', price: 4000 },
  { name: 'GLUTA PUSH 1 SESSION', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 500 },
  { name: 'HIKO THREAD NOSE', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 15000 },
  { name: 'SCLEROTHERAPY', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 5000 },
  { name: 'TRIPECTA BOTOX', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 12500 },
  { name: 'TRIPECTA BOTOX (DOC RICO)', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 9000 },
  { name: 'SWEATOX', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 12500 },
  { name: 'REJURAN (HYDRATION) 1 SESSION', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 15000 },
  { name: 'REJURAN (HYDRATION) 5 SESSIONS', sessions: 5, branch: 'Cainta, Rizal', status: 'active', price: 50000 },
  { name: 'REJURAN HEALER 1 SESSION', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 25000 },
  { name: 'REJURAN (HYDRATION) 5 SESSIONS', sessions: 5, branch: 'Cainta, Rizal', status: 'active', price: 50000 },
  { name: 'SERVICE TEST ADMIN', sessions: 10, branch: 'Pasig City', status: 'active', price: 30000 },
  { name: 'MULTIVITAMIN DRIP 5+1', sessions: 6, branch: 'San Mateo, Rizal', status: 'active', price: 12500 },
  { name: 'PIMPLE INJECT', sessions: 1, branch: 'Pasig City', status: 'active', price: 1000 },
  { name: 'BRIGHT UNDERARM PER SESSION', sessions: 1, branch: 'Pasig City', status: 'active', price: 2500 },
  { name: 'MULTIVITAMIN DRIP FULLY PAID', sessions: 1, branch: 'Pasig City', status: 'active', price: 6000 },
  { name: 'INTIMATE PACKAGE 3', sessions: 10, branch: 'San Mateo, Rizal', status: 'active', price: 30000 },
  { name: 'PIMPLE INJECT', sessions: 4, branch: 'Pasig City', status: 'active', price: 1000 },
  { name: 'RADIANT PUSH PACKAGE', sessions: 10, branch: 'Pasig City', status: 'active', price: 4000 },
  { name: 'TATOO REMOVAL', sessions: 1, branch: 'Pasig City', status: 'active', price: 2000 },
  { name: 'CAUTERIZE MILIA', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 1500 },
  { name: 'IMMUNITY DRIP PACKAGE', sessions: 8, branch: 'Pasig City', status: 'active', price: 10000 },
  { name: 'SCLEROTHERAPY', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 6000 },
  { name: 'CINDERELLA PACKAGE B', sessions: 25, branch: 'San Mateo, Rizal', status: 'active', price: 30000 },
  { name: 'IMAJICA BIGLOW (BRIGHT)', sessions: 5, branch: 'San Mateo, Rizal', status: 'active', price: 12000 },
  { name: 'CARBON BLACKDOLL', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 2000 },
  { name: 'EXIPRO ARMS', sessions: 10, branch: 'San Mateo, Rizal', status: 'active', price: 3500 },
  { name: 'EXIPRO TUMMY', sessions: 10, branch: 'San Mateo, Rizal', status: 'active', price: 3500 },
  { name: 'EMSLIM TUMMY', sessions: 10, branch: 'San Mateo, Rizal', status: 'active', price: 1500 },
  { name: 'EMSLIM ARMS', sessions: 10, branch: 'San Mateo, Rizal', status: 'active', price: 1500 },
  { name: 'EXIPRO BRA LINE', sessions: 10, branch: 'San Mateo, Rizal', status: 'active', price: 1500 },
  { name: 'EXIPRO LOVE HANDLE', sessions: 10, branch: 'San Mateo, Rizal', status: 'active', price: 7500 },
  { name: 'MULTIVITAMIN DRIP 25+10', sessions: 35, branch: 'Pasig City', status: 'active', price: 50000 },
  { name: 'BIO-REVIVE', sessions: 2, branch: 'San Mateo, Rizal', status: 'active', price: 20000 },
  { name: 'BIO-MIEL 6', sessions: 2, branch: 'San Mateo, Rizal', status: 'active', price: 30000 },
  { name: 'GLUTA PUSH', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 500 },
  { name: 'BOTOX TRIFECTA', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 15000 },
  { name: 'SWEATOX', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 12500 },
  { name: 'GLUTA PUSH PACKAGE', sessions: 10, branch: 'San Mateo, Rizal', status: 'active', price: 4000 },
  { name: 'INTIMATE PACKAGE 1', sessions: 2, branch: 'San Mateo, Rizal', status: 'active', price: 15000 },
  { name: 'IMAJICA BACK FACIAL', sessions: 5, branch: 'San Mateo, Rizal', status: 'active', price: 15000 },
  { name: 'IMAJICA REVIVE FULL PAYMENT', sessions: 1, branch: 'Pasig City', status: 'active', price: 10000 },
  { name: 'CAUTERIZE SYRINGOMA', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 3000 },
  { name: 'CAUTERIZE WARTS', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 2000 },
  { name: 'KELOIDS REMOVAL', sessions: 1, branch: 'Pasig City', status: 'active', price: 1500 },
  { name: 'TATTOO REMOVAL', sessions: 1, branch: 'Pasig City', status: 'active', price: 1500 },
  { name: 'OXYBRIGHT FACIAL', sessions: 1, branch: 'Pasig City', status: 'active', price: 2500 },
  { name: 'UNDEREYE FILLER', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 12500 },
  { name: 'WARTS SKIN TAG', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 5000 },
  { name: 'MULTIVITAMIN DRIP 10 + 5 PACKAGE', sessions: 15, branch: 'San Mateo, Rizal', status: 'active', price: 25000 },
  { name: 'PICO LASER (BLACK DOLL)', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 2500 },
  { name: 'SKIN TAG', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 2000 },
  { name: 'LEMON BOTTLE ARMS AND TUMMY', sessions: 3, branch: 'Cainta, Rizal', status: 'active', price: 18000 },
  { name: 'TRIFECTA BOTOX (FOREHEAD, CROW\'S FEET, FROWN)', sessions: 1, branch: 'Pasig City', status: 'active', price: 8500 },
  { name: 'LIP FILLER (DOC RICO)', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 5000 },
  { name: 'MULTIVITAMIN DRIP 20 + 15', sessions: 35, branch: 'San Mateo, Rizal', status: 'active', price: 50000 },
  { name: 'PIMPLE INJECT', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 750 },
  { name: 'MILIA REMOVAL', sessions: 1, branch: 'Pasig City', status: 'active', price: 2500 },
  { name: 'MESO DNA', sessions: 5, branch: 'San Mateo, Rizal', status: 'active', price: 25000 },
  { name: 'UNDEREYE FILLER', sessions: 1, branch: 'Pasig City', status: 'active', price: 8500 },
  { name: 'FLAWLESS UNDERARM 1 SESSION', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 2000 },
  { name: 'IMAJICA SCULPT PACKAGE', sessions: 1, branch: 'Pasig City', status: 'active', price: 5000 },
  { name: 'TATTOO REMOVAL', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 3000 },
  { name: 'PIMPLE INJECT 2 SESSIONS', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 500 },
  { name: 'PIMPLE INJECT 4', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 1000 },
  { name: 'PIMPLE INJECT 3', sessions: 5, branch: 'Cainta, Rizal', status: 'active', price: 1250 },
  { name: 'IMAJICA REVIVE', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 12500 },
  { name: 'CAUTERIZE', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 5000 },
  { name: 'CHEMICAL PEEL (KNEE/ELBOW)', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 2500 },
  { name: 'BLACKDOLL PACKAGE', sessions: 5, branch: 'San Mateo, Rizal', status: 'active', price: 7500 },
  { name: 'HALF LEGS ACNE SCAR TREATMENT', sessions: 1, branch: 'Pasig City', status: 'active', price: 7500 },
  { name: 'CHEMICAL PEEL (NECK)', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 3500 },
  { name: 'LEMON BOTTLE PACKAGES', sessions: 2, branch: 'San Mateo, Rizal', status: 'active', price: 15000 },
  { name: 'LEMON BOTTLE MESO LIP', sessions: 2, branch: 'San Mateo, Rizal', status: 'active', price: 15000 },
  { name: 'KELOID REMOVAL (2X2 SIZE)', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 2500 },
  { name: 'CO2', sessions: 1, branch: 'Pasig City', status: 'active', price: 3000 },
  { name: 'SUBSICION', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 9000 },
  { name: 'IMAJICA SLIM PACKAGE', sessions: 5, branch: 'San Mateo, Rizal', status: 'active', price: 60000 },
  { name: 'PIMPLE INJECT', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 750 },
  { name: 'PROMO AQUAFACIAL', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 999 },
  { name: 'IMAJICA GLIM I SHOTS', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 10000 },
  { name: 'WARTS REMOVAL FACE & NECK', sessions: 1, branch: 'Pasig City', status: 'active', price: 8000 },
  { name: 'GLUTA PUSH', sessions: 1, branch: 'Pasig City', status: 'active', price: 500 },
  { name: 'LEMON BOTTLE PER SESSION', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 5500 },
  { name: 'SYNERGY SCARS TREATMENT', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 20000 },
  { name: 'IMARICA SLIM (GLP)', sessions: 4, branch: 'San Mateo, Rizal', status: 'active', price: 30000 },
  { name: 'JAW TOX', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 10000 },
  { name: 'LIP FILLER', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 10000 },
  { name: 'DIODE (UPPER LIP, LOWER LIP)', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 1000 },
  { name: 'HAPPY HOUR', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 2500 },
  { name: 'CHEMICAL PEEL (ANKLE)', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 4500 },
  { name: 'UNDERARM EXOSOME', sessions: 5, branch: 'San Mateo, Rizal', status: 'active', price: 15000 },
  { name: 'GLOW AND LIFT PROMO', sessions: 1, branch: 'Pasig City', status: 'active', price: 15000 },
  { name: 'LEMON BOTTLE PACKAGES', sessions: 3, branch: 'Pasig City', status: 'active', price: 15000 },
  { name: 'ULTRAFORMER 120', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 10000 },
  { name: 'HAPPY HOUR PROMO EVERY 10AM TO 12NN', sessions: 1, branch: 'Pasig City', status: 'active', price: 2500 },
  { name: 'IMARICA SLIM (GLP) 3 + 1', sessions: 4, branch: 'Pasig City', status: 'active', price: 30000 },
  { name: 'LIFT AND GLOW', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 15000 },
  { name: 'BUTT WHITENING PACKAGE', sessions: 5, branch: 'San Mateo, Rizal', status: 'active', price: 22000 },
  { name: 'IMARICA KELOID SCARS', sessions: 5, branch: 'San Mateo, Rizal', status: 'active', price: 15000 },
  { name: 'PICOLASER FACIAL', sessions: 5, branch: 'Cainta, Rizal', status: 'active', price: 15000 },
  { name: 'CHIN FILLER', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 10000 },
  { name: 'PICO LASER LIPS', sessions: 5, branch: 'Cainta, Rizal', status: 'active', price: 4000 },
  { name: 'REJURAN S', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 10000 },
  { name: 'WARTS FULL FACE AND NECK', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 2000 },
  { name: 'ULTRAFORMER (GLOW AND LIFT)', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 15000 },
  { name: 'BOTOX TRIFECTA/ FILLER/ UNDEREYE', sessions: 1, branch: 'Pasig City', status: 'active', price: 40000 },
  { name: 'TRIFECTA BOTOX / LIP FILLER', sessions: 1, branch: 'Pasig City', status: 'active', price: 20000 },
  { name: 'FROWNLINE (BOTOX)', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 4000 },
  { name: 'ULTRAFORMER PACKAGE', sessions: 3, branch: 'Cainta, Rizal', status: 'active', price: 35000 },
  { name: 'BILLING (ADDITIONAL PAYMENT FROM VAMPIRE TO CLEAR)', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 2500 },
  { name: 'KELOIDS REMOVAL PACKAGE', sessions: 5, branch: 'Pasig City', status: 'active', price: 10000 },
  { name: 'BRAZILLIAN', sessions: 1, branch: 'Pasig City', status: 'active', price: 3000 },
  { name: 'IMARCA SLIM (SLP) 3+1', sessions: 4, branch: 'Pasig City', status: 'active', price: 45000 },
  { name: 'KELOID REMOVAL', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 2000 },
  { name: 'COG THREADS AND FILLER', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 50000 },
  { name: 'VAMPIRE FACIAL', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 7500 },
  { name: 'SLP1 (2ND PACKAGE) 3+1', sessions: 4, branch: 'Cainta, Rizal', status: 'active', price: 45000 },
  { name: 'BOTOX CROW\'S FEET/ ALARTOX', sessions: 1, branch: 'Pasig City', status: 'active', price: 10000 },
  { name: 'NAD DRIP', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 30000 },
  { name: 'SUBSICION, FILLER, BOTOX', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 20000 },
  { name: 'ULTRAFORMER (2D / HIFU)', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 5000 },
  { name: 'HAPPY HOUR', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 2500 },
  { name: 'CHEMICAL PEEL (UNDERARM)', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 2500 },
  { name: 'WARTS REMOVAL FACE & NECK', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 6500 },
  { name: 'IMARCA BRIGHT', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 3500 },
  { name: 'PACKAGE 10 CINDERELLA DRIP', sessions: 10, branch: 'Pasig City', status: 'active', price: 3750 },
  { name: 'CARBON LASER FACIAL', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 3500 },
  { name: 'BARBIE ARMS', sessions: 1, branch: 'Pasig City', status: 'active', price: 3500 },
  { name: 'BIG WARTS REMOVAL FACE', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 1000 },
  { name: 'RADIANT PUSH', sessions: 1, branch: 'Pasig City', status: 'active', price: 1500 },
  { name: 'SWEATOX (PROMO)', sessions: 1, branch: 'Pasig City', status: 'active', price: 10000 },
  { name: 'HIKO', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 10000 },
  { name: 'BARBIE ARMS PER SESSION', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 2500 },
  { name: 'SWEATOX', sessions: 1, branch: 'Pasig City', status: 'active', price: 12500 },
  { name: 'ADD ON\'S (L CARNATINE)', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 500 },
  { name: 'CHEMICAL PEEL (KNEE)', sessions: 5, branch: 'San Mateo, Rizal', status: 'active', price: 2500 },
  { name: 'FULLY PAID IMAJICA REVIVE', sessions: 6, branch: 'Pasig City', status: 'active', price: 12500 },
  { name: 'HAPPY HOUR + BLACKDOLL', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 4000 },
  { name: 'HAPPY HOUR PROMO + OXYBRIGHT', sessions: 1, branch: 'Pasig City', status: 'active', price: 4000 },
  { name: 'S20 ULTRAFORMER HIFU PROMO', sessions: 1, branch: 'Pasig City', status: 'active', price: 5000 },
  { name: 'PIMPLE INJECT (2X)', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 500 },
  { name: 'REJURAN I (UNDEREYE)', sessions: 1, branch: 'Pasig City', status: 'active', price: 15000 },
  { name: 'NASO LABIAL FILLER', sessions: 1, branch: 'Pasig City', status: 'active', price: 10000 },
  { name: 'SUBSICION WITH FILLERS', sessions: 1, branch: 'Pasig City', status: 'active', price: 10000 },
  { name: 'AQUA FACIAL', sessions: 15, branch: 'San Mateo, Rizal', status: 'active', price: 12000 },
  { name: 'PIMPLE INJECT 5+1', sessions: 5, branch: 'Pasig City', status: 'active', price: 1750 },
  { name: 'TCA', sessions: 5, branch: 'Cainta, Rizal', status: 'active', price: 5000 },
  { name: 'IMAJICA SCULPT PACKAGE', sessions: 1, branch: 'Pasig City', status: 'active', price: 10000 },
  { name: 'IMAJICA SLIM (LIPO) 5 + 3', sessions: 6, branch: 'San Mateo, Rizal', status: 'active', price: 45000 },
  { name: 'VITAMIN C (ADD ON)', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 500 },
  { name: 'L-CARNATINE (ADD ON)', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 500 },
  { name: 'COLLAGEN (ADD ON)', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 500 },
  { name: 'B-COMPLEX (ADD ON)', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 500 },
  { name: 'HIKO NOSE THREAD LIFT PACKAGE', sessions: 1, branch: 'Pasig City', status: 'active', price: 15000 },
  { name: 'IMAJICA SLIM (RETATRUITION)', sessions: 4, branch: 'San Mateo, Rizal', status: 'active', price: 35000 },
  { name: 'REJURAN I ( UNDEREYE )', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 15000 },
  { name: 'CHEMICAL PEEL (SLPE)', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 2500 },
  { name: 'KELOID REMOVAL', sessions: 1, branch: 'Pasig City', status: 'active', price: 2000 },
  { name: 'BUTT WHITENING PACKAGE', sessions: 10, branch: 'Pasig City', status: 'inactive', price: 22000 },
  { name: 'ULTIMATE INTIMATE PACKAGE', sessions: 10, branch: 'Pasig City', status: 'active', price: 18000 },
  { name: 'PIMPLE INJECT X 2', sessions: 1, branch: 'Pasig City', status: 'active', price: 500 },
  { name: 'PIMPLE INJECT X 3', sessions: 1, branch: 'Pasig City', status: 'active', price: 750 },
  { name: 'HAPPY HOUR (OXYBRIGHT + COLLAGEN DRIP)', sessions: 1, branch: 'Pasig City', status: 'active', price: 3000 },
  { name: 'IMARICA GLOW', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 3500 },
  { name: 'WARTS REMOVAL ( FACE, CHEST AND BACK )', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 7500 },
  { name: 'UNDERARM EXOSOME', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 10000 },
  { name: 'REJURAN I PACKAGE', sessions: 5, branch: 'Pasig City', status: 'active', price: 50000 },
  { name: 'HIKO NOSE', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 15000 },
  { name: 'MESOLIPO ARMS', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 3500 },
  { name: 'SYNERGY SCAR TX 4 IN 1', sessions: 1, branch: 'Pasig City', status: 'active', price: 15000 },
  { name: 'SYNERGY SCAR TX 6 IN 1', sessions: 1, branch: 'Pasig City', status: 'active', price: 15000 },
  { name: 'SYNERGY SCAR TX 8 IN 1', sessions: 1, branch: 'Pasig City', status: 'active', price: 30000 },
  { name: 'OXYBRIGHT PACKAGE', sessions: 5, branch: 'Pasig City', status: 'active', price: 7500 },
  { name: 'CAUTERIZE WARTS', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 5500 },
  { name: 'PICO LASER UNDERARM', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 1500 },
  { name: 'CAUTERIZE WARTS', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 2500 },
  { name: 'LIP FILLER', sessions: 1, branch: 'Pasig City', status: 'active', price: 10000 },
  { name: 'BACK BLACKHEAD REMOVAL', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 10000 },
  { name: 'CHEMICAL PEEL (MA)', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 2500 },
  { name: 'SUBSICION AND FILLER', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 12500 },
  { name: 'UPGRADE FROM 2IN1 TO 4IN1', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 7500 },
  { name: 'FULL FACE (BODY) 5 SESSIONS', sessions: 5, branch: 'Pasig City', status: 'active', price: 5000 },
  { name: 'WARTS & SKIN TAG REMOVAL', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 12000 },
  { name: 'CAUTERIZE WARTS', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 2000 },
  { name: 'IMAJICA SLIM 5MS PER SESSION', sessions: 1, branch: 'Pasig City', status: 'active', price: 15000 },
  { name: 'CAUTERIZE WARTS', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 5000 },
  { name: 'CAUTERIZE WARTS', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 4500 },
  { name: 'SKINTAG REMOVAL (2 AREA)', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 4500 },
  { name: 'ULTIMATE INTIMATE PACKAGE 2', sessions: 10, branch: 'Pasig City', status: 'active', price: 25000 },
  { name: 'STEMCELL (ACU ONE)', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 1000 },
  { name: '2 LEMON BOTTLE PACKAGE', sessions: 10, branch: 'Pasig City', status: 'active', price: 35000 },
  { name: 'CROWS FEET', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 5000 },
  { name: 'MULTIVITAMIN DRIP 25+10', sessions: 35, branch: 'Cainta, Rizal', status: 'active', price: 50000 },
  { name: 'BARBIE FACE PACKAGE', sessions: 5, branch: 'Pasig City', status: 'active', price: 15000 },
  { name: 'OXYBRIGHT FACIAL', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 7500 },
  { name: 'PINK GLOW (FACE)', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 15000 },
  { name: 'WARTS REMOVAL FACE,NECK,BODY', sessions: 1, branch: 'Pasig City', status: 'active', price: 5500 },
  { name: 'SELF LOVE, GLOW UP PROMO', sessions: 1, branch: 'Pasig City', status: 'active', price: 15000 },
  { name: 'BRAZILLIAN', sessions: 10, branch: 'San Mateo, Rizal', status: 'active', price: 15000 },
  { name: 'PICO LASER LESS', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 1000 },
  { name: 'MESO CHIN', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 1500 },
  { name: 'FRACTIONAL HALF LEGS', sessions: 5, branch: 'San Mateo, Rizal', status: 'active', price: 25000 },
  { name: 'PIMPLE INJECT 50', sessions: 1, branch: 'Pasig City', status: 'active', price: 1500 },
  { name: 'IMAJICA SLIM (GLP1)', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 10000 },
  { name: 'TCA CROSS', sessions: 1, branch: 'Pasig City', status: 'active', price: 5000 },
  { name: 'OXYBRIGHT FACIAL', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 2500 },
  { name: 'OXYBRIGHT FACIAL', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 2500 },
  { name: 'OXYBRIGHT FACIAL', sessions: 1, branch: 'Pasig City', status: 'active', price: 2500 },
  { name: 'CHEST (SYRINGOMA, WARTS, MILLIA, OR SKINTAG)', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 2500 },
  { name: 'CHEST (SYRINGOMA, WARTS, MILLIA, OR SKINTAG)', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 2500 },
  { name: 'CHEST (SYRINGOMA, WARTS, MILLIA, OR SKINTAG)', sessions: 1, branch: 'Pasig City', status: 'active', price: 2500 },
  { name: 'BACK (SYRINGOMA, WARTS, MILLIA, OR SKINTAG)', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 3000 },
  { name: 'BACK (SYRINGOMA, WARTS, MILLIA, OR SKINTAG)', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 3000 },
  { name: 'BACK (SYRINGOMA, WARTS, MILLIA, OR SKINTAG)', sessions: 1, branch: 'Pasig City', status: 'active', price: 3000 },
  { name: 'IMMUNITY DRIP', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 2000 },
  { name: 'IMMUNITY DRIP', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 2000 },
  { name: 'IMMUNITY DRIP', sessions: 1, branch: 'Pasig City', status: 'active', price: 2000 },
  { name: 'PINE BOTTLE (10ML)', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 4000 },
  { name: 'PINE BOTTLE (10ML)', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 4000 },
  { name: 'PINE BOTTLE (10ML)', sessions: 1, branch: 'Pasig City', status: 'active', price: 4000 },
  { name: 'YUVENIS (HA FILLERS)', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 10000 },
  { name: 'YUVENIS (HA FILLERS)', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 10000 },
  { name: 'YUVENIS (HA FILLERS)', sessions: 1, branch: 'Pasig City', status: 'active', price: 10000 },
  { name: 'HIKO NOSE THREAD', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 15000 },
  { name: 'HIKO NOSE THREAD', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 15000 },
  { name: 'HIKO NOSE THREAD', sessions: 1, branch: 'Pasig City', status: 'active', price: 15000 },
  { name: 'NOSE THREAD', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 2500 },
  { name: 'NOSE THREAD', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 2500 },
  { name: 'NOSE THREAD', sessions: 1, branch: 'Pasig City', status: 'active', price: 2500 },
  { name: 'HYDRAFACIAL', sessions: 5, branch: 'San Mateo, Rizal', status: 'active', price: 7500 },
  { name: 'HYDRAFACIAL', sessions: 5, branch: 'Cainta, Rizal', status: 'active', price: 7500 },
  { name: 'HYDRAFACIAL', sessions: 5, branch: 'Pasig City', status: 'active', price: 7500 },
  { name: 'OXYBRIGHT FACIAL', sessions: 5, branch: 'San Mateo, Rizal', status: 'active', price: 7500 },
  { name: 'OXYBRIGHT FACIAL', sessions: 5, branch: 'Cainta, Rizal', status: 'active', price: 7500 },
  { name: 'OXYBRIGHT FACIAL', sessions: 5, branch: 'Pasig City', status: 'active', price: 7500 },
  { name: 'IMAJICA MESO DNA', sessions: 5, branch: 'San Mateo, Rizal', status: 'active', price: 25000 },
  { name: 'IMAJICA MESO DNA', sessions: 5, branch: 'Cainta, Rizal', status: 'active', price: 25000 },
  { name: 'IMAJICA MESO DNA', sessions: 5, branch: 'Pasig City', status: 'active', price: 25000 },
  { name: 'IMAJICA INTIMATE 1', sessions: 5, branch: 'San Mateo, Rizal', status: 'active', price: 20000 },
  { name: 'IMAJICA INTIMATE 1', sessions: 5, branch: 'Cainta, Rizal', status: 'active', price: 20000 },
  { name: 'IMAJICA INTIMATE 1', sessions: 5, branch: 'Pasig City', status: 'active', price: 20000 },
  { name: 'IMAJICA INTIMATE 2', sessions: 10, branch: 'San Mateo, Rizal', status: 'active', price: 20000 },
  { name: 'IMAJICA INTIMATE 2', sessions: 10, branch: 'Cainta, Rizal', status: 'active', price: 20000 },
  { name: 'IMAJICA INTIMATE 2', sessions: 10, branch: 'Pasig City', status: 'active', price: 20000 },
  { name: 'IMAJICA BUTT WHITENING', sessions: 10, branch: 'San Mateo, Rizal', status: 'active', price: 22000 },
  { name: 'IMAJICA BUTT WHITENING', sessions: 10, branch: 'Cainta, Rizal', status: 'active', price: 22000 },
  { name: 'IMAJICA BUTT WHITENING', sessions: 10, branch: 'Pasig City', status: 'active', price: 22000 },
  { name: 'MESO CHIN', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 1500 },
  { name: 'MESO ARMS', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 1500 },
  { name: 'HAPPY HOUR PROMO', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 2500 },
  { name: 'HAPPY HOUR PROMO', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 2500 },
  { name: 'HAPPY HOUR PROMO', sessions: 1, branch: 'Pasig City', status: 'active', price: 2500 },
  { name: 'HAPPY HOUR PROMO', sessions: 1, branch: 'Warehouse', status: 'active', price: 2500 },
  { name: 'PIMPLE INJECT', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 750 },
  { name: 'IMAJICA SLIM SPLIT LEVEL 2', sessions: 5, branch: 'San Mateo, Rizal', status: 'active', price: 35000 },
  { name: 'HAPPY HOUR (OXYBRIGHT/ CARBON LASER)', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 4000 },
  { name: 'HAPPY HOUR (OXYBRIGHT/ CARBON LASER)', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 4000 },
  { name: 'HAPPY HOUR (OXYBRIGHT/ CARBON LASER)', sessions: 1, branch: 'Pasig City', status: 'active', price: 4000 },
  { name: 'UNDERARM EXOSOMES', sessions: 4, branch: 'San Mateo, Rizal', status: 'active', price: 25000 },
  { name: 'UNDERARM EXOSOMES', sessions: 4, branch: 'Cainta, Rizal', status: 'active', price: 25000 },
  { name: 'UNDERARM EXOSOMES', sessions: 4, branch: 'Pasig City', status: 'active', price: 25000 },
  { name: 'PIMPLE INJECT', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 250 },
  { name: 'PIMPLE INJECT', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 750 },
  { name: 'PIMPLE INJECT', sessions: 3, branch: 'Pasig City', status: 'active', price: 750 },
  { name: 'MESO SLIM LEGS CONTOUR', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 5000 },
  { name: 'IMARCA SLIM (LVL 3)', sessions: 4, branch: 'San Mateo, Rizal', status: 'active', price: 45000 },
  { name: 'GLP1 (2ND PACKAGE) 5+1', sessions: 6, branch: 'Cainta, Rizal', status: 'active', price: 45000 },
  { name: 'MESOSLIM CHIN', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 1500 },
  { name: 'GLUTA PUSH', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 500 },
  { name: 'GLUTA PUSH', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 500 },
  { name: 'GLUTA PUSH', sessions: 1, branch: 'Pasig City', status: 'active', price: 500 },
  { name: 'GLUTA PUSH', sessions: 1, branch: 'Warehouse', status: 'active', price: 500 },
  { name: 'WARTS FACE AND NECK', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 2000 },
  { name: 'WARTS FACE AND NECK', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 2000 },
  { name: 'WARTS FACE AND NECK', sessions: 1, branch: 'Pasig City', status: 'active', price: 2000 },
  { name: 'WARTS FACE AND NECK', sessions: 1, branch: 'Warehouse', status: 'active', price: 2000 },
  { name: 'GLOW & LIFT PROMO', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 15000 },
  { name: 'GLOW & LIFT PROMO', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 15000 },
  { name: 'GLOW & LIFT PROMO', sessions: 1, branch: 'Pasig City', status: 'active', price: 15000 },
  { name: 'GLOW & LIFT PROMO', sessions: 1, branch: 'Warehouse', status: 'active', price: 15000 },
  { name: 'JAWTOX / HIFU', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 17500 },
  { name: 'TRIFECTA BOTOX', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 12500 },
  { name: 'KELOIDS REMOVAL (2X2 SIZE)', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 2500 },
  { name: 'SKIN BOOSTER', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 15000 },
  { name: 'WARTS (CHEST AND NAPE)', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 2000 },
  { name: 'CAUTERIZE WARTS FACE', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 1500 },
  { name: 'CAUTERIZE WARTS FACE', sessions: 1, branch: 'Warehouse', status: 'active', price: 1500 },
  { name: 'PIMPLE INJECT', sessions: 1, branch: 'Pasig City', status: 'active', price: 250 },
  { name: 'GLUTA COL PLACENTA', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 1000 },
  { name: 'REJURAN 5 PER SESSION', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 15000 },
  { name: 'REJURAN 5 PER SESSION', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 15000 },
  { name: 'REJURAN 5 PER SESSION', sessions: 1, branch: 'Pasig City', status: 'active', price: 15000 },
  { name: 'REJURAN 5 PER SESSION', sessions: 1, branch: 'Warehouse', status: 'active', price: 15000 },
  { name: 'KELOIDS REMOVAL PACKAGE', sessions: 5, branch: 'Pasig City', status: 'active', price: 25000 },
  { name: 'ANESTHESIA', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 500 },
  { name: 'H-HOUR + RO + WARTS / HYDRO', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 4500 },
  { name: 'PIMPLE INJECT', sessions: 3, branch: 'Pasig City', status: 'active', price: 500 },
  { name: 'STEMM CELL (ADD ON)', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 1000 },
  { name: 'UNDERARM (DIODE CH. LASER)', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 3000 },
  { name: 'WARTS', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 1500 },
  { name: 'CAUTERIZE WARTS', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 2000 },
  { name: 'ULTOX (HIFU)', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 15000 },
  { name: 'IMAJICA SLIM 5MG GLP1', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 45000 },
  { name: 'IMAJICA SLIM 5MG GLP1', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 45000 },
  { name: 'IMAJICA SLIM 5MG GLP1', sessions: 1, branch: 'Pasig City', status: 'active', price: 45000 },
  { name: 'IMAJICA SLIM 5MG GLP1', sessions: 1, branch: 'Warehouse', status: 'active', price: 45000 },
  { name: 'IMARCA SLIM 2.5MG PER SESSION', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 10000 },
  { name: 'IMARCA SLIM 2.5MG PER SESSION', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 10000 },
  { name: 'IMARCA SLIM 2.5MG PER SESSION', sessions: 1, branch: 'Pasig City', status: 'active', price: 10000 },
  { name: 'IMARCA SLIM 2.5MG PER SESSION', sessions: 1, branch: 'Warehouse', status: 'active', price: 10000 },
  { name: 'IMARCA SCULPT', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 10000 },
  { name: 'TCA CROSS PER SESSION', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 5000 },
  { name: 'TCA CROSS PER SESSION', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 5000 },
  { name: 'TCA CROSS PER SESSION', sessions: 1, branch: 'Pasig City', status: 'active', price: 5000 },
  { name: 'TCA CROSS PER SESSION', sessions: 1, branch: 'Warehouse', status: 'active', price: 5000 },
  { name: 'IMARCA REVIVE PER SESSION', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 9000 },
  { name: 'DELETED RECORDS JULY', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 12002 },
  { name: 'XIN1 SCAR PROTOCOL', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 32030 },
  { name: 'CAUTERIZE WARTS FACE AND NECK', sessions: 1, branch: 'Cainta, Rizal', status: 'active', price: 8000 },
  { name: 'COLLAGEN (ADD ON)', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 500 },
  { name: 'MULTIVITAMIN DRIP', sessions: 1, branch: '', status: 'active', price: 2500 },
  { name: 'K-GLOW FACIAL', sessions: 1, branch: '', status: 'active', price: 2500 },
  { name: 'CHARCOAL LASER FACIAL', sessions: 1, branch: '', status: 'active', price: 2500 },
  { name: 'PICO LASER FACIAL', sessions: 1, branch: '', status: 'active', price: 2500 },
  { name: 'HYDRAFACIAL', sessions: 1, branch: '', status: 'active', price: 2500 },
  { name: 'OXYBRIGHT FACIAL', sessions: 1, branch: '', status: 'active', price: 2500 },
  { name: 'ACNE CURE FACIAL', sessions: 1, branch: '', status: 'active', price: 2500 },
  { name: 'IMARCA AQUA', sessions: 1, branch: '', status: 'active', price: 2000 },
  { name: 'IMARCA CELEBRITY', sessions: 1, branch: '', status: 'active', price: 4500 },
  { name: 'IMARCA CLEAR', sessions: 1, branch: '', status: 'active', price: 4500 },
  { name: 'MILLIA REMOVAL', sessions: 1, branch: '', status: 'active', price: 1500 },
  { name: 'WARTS REMOVAL', sessions: 1, branch: '', status: 'active', price: 1500 },
  { name: 'SKINTAG REMOVAL', sessions: 1, branch: '', status: 'active', price: 1500 },
  { name: 'SYRINGOMA REMOVAL', sessions: 1, branch: '', status: 'active', price: 1500 },
  { name: 'SYRINGOMA REMOVAL (NECK)', sessions: 1, branch: '', status: 'active', price: 1500 },
  { name: 'SYRINGOMA REMOVAL (FACE AND NECK)', sessions: 1, branch: '', status: 'active', price: 2500 },
  { name: 'SYRINGOMA REMOVAL (CHEST)', sessions: 1, branch: '', status: 'active', price: 2500 },
  { name: 'SYRINGOMA REMOVAL (BACK)', sessions: 1, branch: '', status: 'active', price: 2500 },
  { name: 'SKINTAG REMOVAL (NECK)', sessions: 1, branch: '', status: 'active', price: 1500 },
  { name: 'SKINTAG REMOVAL (FACE AND NECK)', sessions: 1, branch: '', status: 'active', price: 2500 },
  { name: 'SKINTAG REMOVAL (CHEST)', sessions: 1, branch: '', status: 'active', price: 2500 },
  { name: 'SKINTAG REMOVAL (BACK)', sessions: 1, branch: '', status: 'active', price: 2500 },
  { name: 'WARTS REMOVAL (NECK)', sessions: 1, branch: '', status: 'active', price: 1500 },
  { name: 'WARTS REMOVAL (FACE AND NECK)', sessions: 1, branch: '', status: 'active', price: 2500 },
  { name: 'WARTS REMOVAL (CHEST)', sessions: 1, branch: '', status: 'active', price: 2500 },
  { name: 'WARTS REMOVAL (BACK)', sessions: 1, branch: '', status: 'active', price: 2500 },
  { name: 'MILLIA REMOVAL (NECK)', sessions: 1, branch: '', status: 'active', price: 1500 },
  { name: 'MILLIA REMOVAL (FACE AND NECK)', sessions: 1, branch: '', status: 'active', price: 2500 },
  { name: 'MILLIA REMOVAL (CHEST)', sessions: 1, branch: '', status: 'active', price: 2500 },
  { name: 'MILLIA REMOVAL (BACK)', sessions: 1, branch: '', status: 'active', price: 2500 },
  { name: 'DIODE (UPPER LIP)', sessions: 1, branch: '', status: 'active', price: 500 },
  { name: 'DIODE (FULL FACE)', sessions: 1, branch: '', status: 'active', price: 1500 },
  { name: 'DIODE (UNDERARM)', sessions: 1, branch: '', status: 'active', price: 1500 },
  { name: 'DIODE (FULL ARMS)', sessions: 1, branch: '', status: 'active', price: 2500 },
  { name: 'DIODE (BRAZILLIAN)', sessions: 1, branch: '', status: 'active', price: 2000 },
  { name: 'DIODE (HALF LEGS)', sessions: 1, branch: '', status: 'active', price: 2000 },
  { name: 'DIODT (FULL LEGS)', sessions: 1, branch: '', status: 'active', price: 5000 },
  { name: 'CHARCOAL LASER (UNDERARM)', sessions: 1, branch: '', status: 'active', price: 1500 },
  { name: 'CHARCOAL LASER (NAPE)', sessions: 1, branch: '', status: 'active', price: 1500 },
  { name: 'CHARCOAL LASER (ELBOW)', sessions: 1, branch: '', status: 'active', price: 1500 },
  { name: 'CHARCOAL LASER (KNEE)', sessions: 1, branch: '', status: 'active', price: 1500 },
  { name: 'CHARCOAL LASER (BUTT)', sessions: 1, branch: '', status: 'active', price: 2500 },
  { name: 'CHARCOAL LASER (BIKINI)', sessions: 1, branch: '', status: 'active', price: 2500 },
  { name: 'CHEMICAL PEELING (UNDERARM WHITENING)', sessions: 1, branch: '', status: 'active', price: 2500 },
  { name: 'CHEMICAL PEELING (NAPE WHITENING)', sessions: 1, branch: '', status: 'active', price: 2500 },
  { name: 'CHEMICAL PEELING (KNEE AND ELBOW)', sessions: 1, branch: '', status: 'active', price: 2500 },
  { name: 'CHEMICAL PEELING (GROIN WHITENING)', sessions: 1, branch: '', status: 'active', price: 3000 },
  { name: 'CHEMICAL PEELING (BUTT WHITENING)', sessions: 1, branch: '', status: 'active', price: 3000 },
  { name: 'BACKIAL', sessions: 1, branch: '', status: 'active', price: 2000 },
  { name: 'V-FACIAL', sessions: 1, branch: '', status: 'active', price: 1000 },
  { name: 'RADIANT GLOW PUSH', sessions: 1, branch: '', status: 'active', price: 500 },
  { name: 'DRIP (IMMUNITY DRIP)', sessions: 1, branch: '', status: 'active', price: 2000 },
  { name: 'DRIP (SLENDER DRIP)', sessions: 1, branch: '', status: 'active', price: 2000 },
  { name: 'DRIP (AGE REVERSING DRIP)', sessions: 1, branch: '', status: 'active', price: 2000 },
  { name: 'DRIP (MULTIVITAMIN DRIP)', sessions: 1, branch: '', status: 'active', price: 2500 },
  { name: 'EXOPRO (FACE AND NECK)', sessions: 1, branch: '', status: 'active', price: 1500 },
  { name: 'EXOPRO (ARMS)', sessions: 1, branch: '', status: 'active', price: 1500 },
  { name: 'EXOPRO (TUMMY)', sessions: 1, branch: '', status: 'active', price: 2500 },
  { name: 'EXOPRO (THIGHS)', sessions: 1, branch: '', status: 'active', price: 2500 },
  { name: 'MESO WITH EXOPRO (FACE AND NECK)', sessions: 1, branch: '', status: 'active', price: 2500 },
  { name: 'MESO WITH EXOPRO (ARMS)', sessions: 1, branch: '', status: 'active', price: 2500 },
  { name: 'MESO WITH EXOPRO (TUMMY)', sessions: 1, branch: '', status: 'active', price: 3500 },
  { name: 'MESO WITH EXOPRO (THIGHS)', sessions: 1, branch: '', status: 'active', price: 4500 },
  { name: 'MESOLIPO (LIPOLAB 10ML)', sessions: 1, branch: '', status: 'active', price: 2500 },
  { name: 'MESOLIPO (KABELLINE 10ML)', sessions: 1, branch: '', status: 'active', price: 3500 },
  { name: 'MESOLIPO (LEMON BOTTLE 10ML)', sessions: 1, branch: '', status: 'active', price: 6500 },
  { name: 'EMSLIM 30 MINS', sessions: 1, branch: '', status: 'active', price: 1500 },
  { name: 'MESOSLIM FACE CONTOUR', sessions: 1, branch: '', status: 'active', price: 3000 },
  { name: 'MESOSLIM ARMS CONTOUR', sessions: 1, branch: '', status: 'active', price: 3500 },
  { name: 'MESOSLIM BRA LINE CONTOUR', sessions: 1, branch: '', status: 'active', price: 3500 },
  { name: 'MESO LOVE HANDLE CONTOUR', sessions: 1, branch: '', status: 'active', price: 3500 },
  { name: 'MESOSLIM TUMMY CONTOUR', sessions: 1, branch: '', status: 'active', price: 4000 },
  { name: 'MESOSLIM BUTT CONTOUR', sessions: 1, branch: '', status: 'active', price: 4000 },
  { name: 'MESOSLIM LEGS CONTOUR', sessions: 1, branch: '', status: 'active', price: 5000 },
  { name: 'MESOSLIM BODY CONTOUR', sessions: 1, branch: '', status: 'active', price: 15000 },
  { name: 'ULTRAFORMER HIFU', sessions: 1, branch: '', status: 'active', price: 10000 },
  { name: 'FRACTIONAL (FULL FACE)', sessions: 1, branch: '', status: 'active', price: 4000 },
  { name: 'FRACTIONAL (HALF ARMS)', sessions: 1, branch: '', status: 'active', price: 4000 },
  { name: 'FRACTIONAL (FULL ARMS)', sessions: 1, branch: '', status: 'active', price: 7000 },
  { name: 'FRACTIONAL (TUMMY)', sessions: 1, branch: '', status: 'active', price: 7000 },
  { name: 'FRACTIONAL (HALF LEGS)', sessions: 1, branch: '', status: 'active', price: 7500 },
  { name: 'FRACTIONAL (FULL LEGS)', sessions: 1, branch: '', status: 'active', price: 10000 },
  { name: 'MICRONEEDLING', sessions: 1, branch: '', status: 'active', price: 3000 },
  { name: 'SPANISH PEEL', sessions: 1, branch: '', status: 'active', price: 2000 },
  { name: 'TCA PEEL', sessions: 1, branch: '', status: 'active', price: 5000 },
  { name: 'PRP VAMPIRE', sessions: 1, branch: '', status: 'active', price: 5000 },
  { name: 'SUBSICION', sessions: 1, branch: '', status: 'active', price: 5000 },
  { name: 'MESO SCAR DNA', sessions: 5, branch: '', status: 'active', price: 20000 },
  { name: 'MESO SCAR DNA', sessions: 1, branch: '', status: 'active', price: 5000 },
  { name: 'ACNE FILLER INJ.', sessions: 5, branch: '', status: 'active', price: 35000 },
  { name: 'ACNE FILLER INJ.', sessions: 1, branch: '', status: 'active', price: 10000 },
  { name: '2IN1 FRACTIONAL AND PRP', sessions: 1, branch: '', status: 'active', price: 9000 },
  { name: '2IN1 SUBSICION AND FILLER', sessions: 1, branch: '', status: 'active', price: 12500 },
  { name: '3IN1 TCA, FRACTIONAL, & PRP', sessions: 1, branch: '', status: 'active', price: 15000 },
  { name: '4IN1 SUBSICION, TCA, FRACTIONAL, AND PRP', sessions: 1, branch: '', status: 'active', price: 20000 },
  { name: '5IN1 SUBSICION, TCA, FRACTIONAL, PRP, AND MESODNA', sessions: 1, branch: '', status: 'active', price: 25000 },
  { name: '5IN1 SUBSICION, TCA, FRACTIONAL, PRP, AND REJURAN S', sessions: 1, branch: '', status: 'active', price: 30000 },
  { name: 'MESOMELA', sessions: 1, branch: '', status: 'active', price: 8000 },
  { name: 'REJURAN HEALER', sessions: 1, branch: '', status: 'active', price: 25000 },
  { name: 'REJURAN HB (HYDRATION)', sessions: 1, branch: '', status: 'active', price: 15000 },
  { name: 'REJURAN I (UNDER EYE)', sessions: 1, branch: '', status: 'active', price: 15000 },
  { name: 'REJURAN S (SCARS)', sessions: 1, branch: '', status: 'active', price: 15000 },
  { name: 'CROWN NG GLORY (H.I.R.T.S)', sessions: 1, branch: '', status: 'active', price: 7000 },
  { name: 'EYEBROW LIFT (10 UNITS)', sessions: 1, branch: '', status: 'active', price: 2500 },
  { name: 'CROW\'S FEET (20 UNITS)', sessions: 1, branch: '', status: 'active', price: 5000 },
  { name: 'FROWN LINES (20 UNITS)', sessions: 1, branch: '', status: 'active', price: 5000 },
  { name: 'ALARTOX (20 UNITS)', sessions: 1, branch: '', status: 'active', price: 5000 },
  { name: 'FOREHEAD LINES (30 UNITS)', sessions: 1, branch: '', status: 'active', price: 7500 },
  { name: 'JAWTOX (50 UNITS)', sessions: 1, branch: '', status: 'active', price: 12500 },
  { name: 'SWEATOX (100 UNITS)', sessions: 1, branch: '', status: 'active', price: 25000 },
  { name: 'MELASMA', sessions: 1, branch: '', status: 'active', price: 10000 },
  { name: 'JUVEDERM', sessions: 1, branch: '', status: 'active', price: 20000 },
  { name: 'PLLA SCULPTRA', sessions: 1, branch: '', status: 'active', price: 29000 },
  { name: 'PLLA H-PLLA', sessions: 1, branch: '', status: 'active', price: 25000 },
  { name: 'HIKO NOSE THREADLIFT 8PC', sessions: 1, branch: '', status: 'active', price: 15000 },
  { name: 'NOSE THREADS', sessions: 1, branch: '', status: 'active', price: 2500 },
  { name: 'FOX EYE THREADS', sessions: 1, branch: '', status: 'active', price: 4000 },
  { name: 'COG THREADS', sessions: 1, branch: '', status: 'active', price: 3000 },
  { name: 'MONO THREADS', sessions: 1, branch: '', status: 'active', price: 150 },
  { name: 'PINK GLOW', sessions: 1, branch: '', status: 'active', price: 8000 },
  { name: 'NCTF', sessions: 1, branch: '', status: 'active', price: 20000 },
  { name: 'LUMILO', sessions: 1, branch: '', status: 'active', price: 25000 },
  { name: 'PROFHILO', sessions: 1, branch: '', status: 'active', price: 20000 },
  { name: 'LIP BOOSTER (BACIO)', sessions: 1, branch: '', status: 'active', price: 15000 },
  { name: 'ASCE+ FOR FACE', sessions: 1, branch: '', status: 'active', price: 15000 },
  { name: 'ASCE+ FOR HAIR', sessions: 1, branch: '', status: 'active', price: 15000 },
  { name: 'ASCE+ FOR INTIMATE', sessions: 1, branch: '', status: 'active', price: 15000 },
  { name: 'HIFU ONLY', sessions: 1, branch: '', status: 'active', price: 3000 },
  { name: 'CAUTERIZE FACE', sessions: 1, branch: '', status: 'active', price: 4000 },
  { name: 'CAUTERIZE SKIN TAB', sessions: 1, branch: '', status: 'active', price: 3500 },
  { name: 'AQUA FACIAL PROMO', sessions: 1, branch: '', status: 'active', price: 1000 },
  { name: 'CHARCOAL LASER (HALF ARM)', sessions: 1, branch: '', status: 'active', price: 3500 },
  { name: 'CAUTERIZE WARTS (BODY)', sessions: 1, branch: '', status: 'active', price: 2500 },
  { name: 'CAUTERIZE WARTS (FACE AND NECK)', sessions: 1, branch: '', status: 'active', price: 4500 },
  { name: 'EXOPRO 4+1 PACKAGE', sessions: 5, branch: '', status: 'active', price: 60000 },
  { name: 'TRIFECTA BOTOX', sessions: 1, branch: '', status: 'active', price: 12500 },
  { name: 'GLOTEN NASOLABIAL', sessions: 1, branch: '', status: 'active', price: 20000 },
  { name: 'LIP FILLER', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 10000 },
  { name: 'NEFERTITI BOTOX', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 5000 },
  { name: 'TRIFECTA BOTOX', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 10000 },
  { name: 'SWEATOX (50 UNITS)', sessions: 1, branch: '', status: 'active', price: 12500 },
  { name: 'BABY BOTOX FOR GLABELLAR', sessions: 1, branch: '', status: 'active', price: 2500 },
  { name: 'CAUTERY (NOSE)', sessions: 1, branch: 'San Mateo, Rizal', status: 'active', price: 4000 },
  { name: 'BUTT WHITENING PACKAGE', sessions: 5, branch: 'San Mateo, Rizal', status: 'active', price: 22000 },
  { name: 'CAUTERIZE WARTS (FACE AND NECK)', sessions: 1, branch: '', status: 'active', price: 2500 },
  { name: 'VAMPIRE FACIAL PROMO (1+1)', sessions: 2, branch: '', status: 'active', price: 6000 },
  { name: 'CAUTERIZE MILLIA FACE', sessions: 1, branch: '', status: 'active', price: 3000 },
]
