import { useEffect, useMemo, useState } from 'react'
import { FileSpreadsheet, Filter, Search } from 'lucide-react'
import { toast } from 'sonner'
import { AdminPageBanner } from '@/components/ui/AdminPageBanner'
import { Badge } from '@/components/ui/Badge'
import { Button } from '@/components/ui/Button'
import { Card } from '@/components/ui/Card'
import {
  bestSellingTreatments,
  defaultAnalyticsRange,
  exportCsv,
  getAnalyticsSales,
  subscribeAnalytics,
} from '@/services/analyticsService'
import { preloadSalesData } from '@/services/salesService'
import { formatPesoExact } from '@/utils/currency'
import { cn } from '@/utils/cn'

export function BestSellingTreatmentsPage() {
  const range = defaultAnalyticsRange()
  const [sales, setSales] = useState(() => getAnalyticsSales())
  const [fromDraft, setFromDraft] = useState(range.from)
  const [toDraft, setToDraft] = useState(range.to)
  const [from, setFrom] = useState(range.from)
  const [to, setTo] = useState(range.to)
  const [branchDraft, setBranchDraft] = useState('all')
  const [branch, setBranch] = useState('all')
  const [queryDraft, setQueryDraft] = useState('')
  const [query, setQuery] = useState('')
  const [pageSize, setPageSize] = useState(10)
  const [page, setPage] = useState(1)

  useEffect(() => {
    let cancelled = false
    void preloadSalesData().then(() => {
      if (!cancelled) setSales(getAnalyticsSales())
    })
    return subscribeAnalytics(() => {
      if (!cancelled) setSales(getAnalyticsSales())
    })
  }, [])

  const branchOptions = useMemo(() => {
    const set = new Set(
      getAnalyticsSales()
        .filter((s) => s.itemType === 'service' || s.itemType === 'package')
        .map((s) => s.branchName),
    )
    return ['all', ...[...set].sort()]
  }, [sales])

  const rows = useMemo(
    () => bestSellingTreatments(sales, from, to, branch),
    [sales, from, to, branch],
  )

  const filtered = useMemo(() => {
    if (!query) return rows
    const q = query.toLowerCase()
    return rows.filter((r) => r.treatmentName.toLowerCase().includes(q))
  }, [rows, query])

  const totalBooked = filtered.reduce((s, r) => s + r.totalBooked, 0)
  const totalRevenue = filtered.reduce((s, r) => s + r.totalRevenue, 0)

  const pageCount = Math.max(1, Math.ceil(filtered.length / pageSize))
  const pageRows = filtered.slice((page - 1) * pageSize, page * pageSize)

  function applyFilter() {
    setFrom(fromDraft)
    setTo(toDraft)
    setBranch(branchDraft)
    setPage(1)
  }

  function handleExport() {
    exportCsv(
      `imajica-best-selling-treatments-${from}-${to}.csv`,
      ['Rank', 'Treatment', 'Type', 'Total Booked', 'Total Revenue'],
      filtered.map((r) => [
        String(r.rank),
        r.treatmentName,
        r.type,
        String(r.totalBooked),
        String(r.totalRevenue),
      ]),
    )
    toast.success('Exported best selling treatments')
  }

  return (
    <div className="space-y-5">
      <AdminPageBanner
        title="Best Selling Treatments"
        description="Monitor and analyze bookings count, type, and total proportional revenue generated by all services and packages."
      />

      <Card className="p-4 sm:p-5">
        <div className="flex flex-wrap items-end gap-3">
          <label className="text-xs text-slate-ui">
            Branch
            <select
              value={branchDraft}
              onChange={(e) => setBranchDraft(e.target.value)}
              className="mt-1 block min-w-[160px] rounded-[8px] border border-border bg-white px-3 py-2 text-sm"
            >
              {branchOptions.map((b) => (
                <option key={b} value={b}>
                  {b === 'all' ? 'All Branches' : b}
                </option>
              ))}
            </select>
          </label>
          <label className="text-xs text-slate-ui">
            From
            <input
              type="date"
              value={fromDraft}
              onChange={(e) => setFromDraft(e.target.value)}
              className="mt-1 block rounded-[8px] border border-border bg-white px-3 py-2 text-sm"
            />
          </label>
          <label className="text-xs text-slate-ui">
            To
            <input
              type="date"
              value={toDraft}
              onChange={(e) => setToDraft(e.target.value)}
              className="mt-1 block rounded-[8px] border border-border bg-white px-3 py-2 text-sm"
            />
          </label>
          <Button type="button" onClick={applyFilter} className="gap-1.5">
            <Filter className="h-3.5 w-3.5" />
            Filter
          </Button>
          <Button type="button" onClick={handleExport} className="ml-auto gap-1.5">
            <FileSpreadsheet className="h-3.5 w-3.5" />
            Export Excel
          </Button>
        </div>
      </Card>

      <div className="grid gap-3 sm:grid-cols-2">
        <Card className="p-4">
          <p className="text-[11px] font-semibold uppercase tracking-wide text-slate-ui">
            Total Treatments Booked
          </p>
          <p className="mt-2 font-metric text-3xl font-semibold tracking-tight text-[#073D2C]">{totalBooked}</p>
          <p className="mt-1 text-[11px] text-slate-ui">
            Count of all services &amp; packages booked.
          </p>
        </Card>
        <Card className="p-4">
          <p className="text-[11px] font-semibold uppercase tracking-wide text-slate-ui">
            Gross Treatment Revenue
          </p>
          <p className="mt-2 font-metric text-3xl font-semibold tracking-tight text-[#073D2C]">
            {formatPesoExact(totalRevenue)}
          </p>
          <p className="mt-1 text-[11px] text-slate-ui">
            Proportional revenue from all treatments.
          </p>
        </Card>
      </div>

      <Card className="p-4 sm:p-5">
        <div className="flex flex-wrap items-center gap-3">
          <label className="text-xs text-slate-ui">
            Show
            <select
              value={pageSize}
              onChange={(e) => {
                setPageSize(Number(e.target.value))
                setPage(1)
              }}
              className="ml-1 rounded-[8px] border border-border bg-white px-2 py-2 text-sm"
            >
              {[10, 25, 50].map((n) => (
                <option key={n} value={n}>
                  {n}
                </option>
              ))}
            </select>{' '}
            entries
          </label>
          <div className="relative ml-auto min-w-[220px] flex-1 sm:max-w-sm">
            <Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-ui" />
            <input
              value={queryDraft}
              onChange={(e) => setQueryDraft(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === 'Enter') {
                  setQuery(queryDraft.trim())
                  setPage(1)
                }
              }}
              placeholder="Search treatment..."
              className="w-full rounded-[8px] border border-border bg-white py-2 pl-9 pr-3 text-sm"
            />
          </div>
          <Button
            type="button"
            onClick={() => {
              setQuery(queryDraft.trim())
              setPage(1)
            }}
          >
            Search
          </Button>
        </div>

        <div className="mt-4 overflow-x-auto">
          <table className="min-w-full text-left text-sm">
            <thead className="text-[11px] uppercase tracking-wide text-slate-ui">
              <tr className="border-b border-border">
                <th className="px-2 py-3">Rank</th>
                <th className="px-2 py-3">Treatment Name</th>
                <th className="px-2 py-3">Type</th>
                <th className="px-2 py-3">Total Booked</th>
                <th className="px-2 py-3">Total Revenue</th>
              </tr>
            </thead>
            <tbody>
              {pageRows.map((r) => (
                <tr key={r.treatmentName} className="border-t border-border/70 hover:bg-ivory-100">
                  <td className="px-2 py-3">
                    <RankBadge rank={r.rank} />
                  </td>
                  <td className="px-2 py-3 font-semibold text-[#073D2C]">{r.treatmentName}</td>
                  <td className="px-2 py-3">
                    {r.type === 'Package' ? (
                      <Badge variant="orange">Package</Badge>
                    ) : (
                      <Badge variant="info">Service</Badge>
                    )}
                  </td>
                  <td className="px-2 py-3">{r.totalBooked}</td>
                  <td className="px-2 py-3 font-semibold">{formatPesoExact(r.totalRevenue)}</td>
                </tr>
              ))}
              {pageRows.length === 0 && (
                <tr>
                  <td colSpan={5} className="px-2 py-8 text-center text-slate-ui">
                    No treatment bookings in this range.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>

        <div className="mt-3 flex items-center justify-between text-xs text-slate-ui">
          <span>
            Showing {(page - 1) * pageSize + (pageRows.length ? 1 : 0)}–
            {Math.min(page * pageSize, filtered.length)} of {filtered.length}
          </span>
          <div className="flex gap-2">
            <Button
              type="button"
              variant="secondary"
              disabled={page <= 1}
              onClick={() => setPage((p) => p - 1)}
            >
              Prev
            </Button>
            <Button
              type="button"
              variant="secondary"
              disabled={page >= pageCount}
              onClick={() => setPage((p) => p + 1)}
            >
              Next
            </Button>
          </div>
        </div>
      </Card>
    </div>
  )
}

function RankBadge({ rank }: { rank: number }) {
  if (rank === 1) {
    return (
      <span className="inline-flex h-8 w-8 items-center justify-center rounded-full bg-amber-400 text-xs font-bold text-white">
        1
      </span>
    )
  }
  if (rank === 2) {
    return (
      <span className="inline-flex h-8 w-8 items-center justify-center rounded-full bg-slate-300 text-xs font-bold text-slate-700">
        2
      </span>
    )
  }
  if (rank === 3) {
    return (
      <span className="inline-flex h-8 w-8 items-center justify-center rounded-full bg-amber-700 text-xs font-bold text-white">
        3
      </span>
    )
  }
  return (
    <span
      className={cn(
        'inline-flex h-8 w-8 items-center justify-center rounded-full bg-ivory-100 text-xs font-semibold text-[#073D2C]',
      )}
    >
      {rank}
    </span>
  )
}
